\i /docker-entrypoint-initdb.d/001_base_schema.sql
\i /docker-entrypoint-initdb.d/002_usuario_gestao.sql
\i /docker-entrypoint-initdb.d/003_produtos_nfe_base.sql
\i /docker-entrypoint-initdb.d/004_pessoa_base.sql
\i /docker-entrypoint-initdb.d/005_vendas_financeiro_base.sql
\i /docker-entrypoint-initdb.d/006_produto_codigo_automatico.sql
\i /docker-entrypoint-initdb.d/007_unaccent_support.sql
\i /docker-entrypoint-initdb.d/008_configuracao_fiscal.sql
\i /docker-entrypoint-initdb.d/009_financeiro_baixa_historico.sql
\i /docker-entrypoint-initdb.d/010_configuracao_gateway.sql
\i /docker-entrypoint-initdb.d/011_gateway_config_payments_schema.sql
\i /docker-entrypoint-initdb.d/012_produto_unidade_padrao_simples.sql
\i /docker-entrypoint-initdb.d/013_condicao_boleto_venda.sql
\i /docker-entrypoint-initdb.d/014_message_whatsapp_config.sql
\i /docker-entrypoint-initdb.d/015_usuario_master_onboarding.sql
