-- Cria um usuario exclusivo para a base db_v12.
-- Execute como superusuario (ex.: postgres) na VPS.
--
-- Ajuste a senha antes de rodar em producao.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_roles
    WHERE rolname = 'v12_user'
  ) THEN
    CREATE ROLE v12_user
      LOGIN
      PASSWORD 'TroqueEstaSenhaForte_2026!';
  ELSE
    ALTER ROLE v12_user
      WITH LOGIN
      PASSWORD 'TroqueEstaSenhaForte_2026!';
  END IF;
END $$;

ALTER ROLE v12_user SET client_encoding TO 'UTF8';
ALTER ROLE v12_user SET default_transaction_isolation TO 'read committed';
ALTER ROLE v12_user SET timezone TO 'America/Sao_Paulo';

GRANT CONNECT, TEMPORARY ON DATABASE db_v12 TO v12_user;
ALTER DATABASE db_v12 OWNER TO v12_user;

GRANT USAGE, CREATE ON SCHEMA public TO v12_user;
ALTER SCHEMA public OWNER TO v12_user;

CREATE SCHEMA IF NOT EXISTS payments AUTHORIZATION v12_user;
GRANT USAGE, CREATE ON SCHEMA payments TO v12_user;
ALTER SCHEMA payments OWNER TO v12_user;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO v12_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO v12_user;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO v12_user;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA payments TO v12_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA payments TO v12_user;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA payments TO v12_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT ALL PRIVILEGES ON TABLES TO v12_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT ALL PRIVILEGES ON SEQUENCES TO v12_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT ALL PRIVILEGES ON FUNCTIONS TO v12_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA payments
  GRANT ALL PRIVILEGES ON TABLES TO v12_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA payments
  GRANT ALL PRIVILEGES ON SEQUENCES TO v12_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA payments
  GRANT ALL PRIVILEGES ON FUNCTIONS TO v12_user;
