CREATE TABLE IF NOT EXISTS fiscal_config (
  config_id INTEGER PRIMARY KEY CHECK (config_id = 1),
  tenant_erp_id INTEGER NOT NULL,
  ambiente_nfe TEXT NOT NULL DEFAULT '2',
  crt TEXT NOT NULL DEFAULT '3',
  cnae TEXT,
  natureza_operacao_padrao TEXT,
  nfce_habilitada INTEGER NOT NULL DEFAULT 0,
  serie_nfce_padrao INTEGER NOT NULL DEFAULT 1,
  proximo_numero_nfce INTEGER NOT NULL DEFAULT 1,
  nfce_id_token_csc TEXT,
  nfce_csc TEXT,
  nfce_ind_pres_padrao TEXT NOT NULL DEFAULT '1',
  emitente_nome_razao TEXT,
  emitente_nome_fantasia TEXT,
  emitente_cpf_cnpj TEXT,
  emitente_inscricao_estadual TEXT,
  emitente_inscricao_municipal TEXT,
  emitente_email TEXT,
  emitente_telefone TEXT,
  emitente_cep TEXT,
  emitente_logradouro TEXT,
  emitente_numero TEXT,
  emitente_complemento TEXT,
  emitente_bairro TEXT,
  emitente_cidade TEXT,
  emitente_uf TEXT,
  emitente_codigo_ibge TEXT,
  emitente_pais TEXT,
  responsavel_tecnico_cnpj TEXT,
  responsavel_tecnico_nome TEXT,
  responsavel_tecnico_contato TEXT,
  responsavel_tecnico_email TEXT,
  responsavel_tecnico_telefone TEXT,
  certificado_nome_arquivo TEXT,
  certificado_conteudo_base64 TEXT,
  certificado_senha TEXT,
  sincronizado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_fiscal_config_tenant
  ON fiscal_config(tenant_erp_id, nfce_habilitada);
